### ISSUE TITLE
Download pdf button and opening in new window

### ISSUE THREAD

**Issue by cofiem** [belowtheline/site_2014#13]
- it is not clear that clicking the 'download pdf' button will generate a pdf with the ballot information. This needs to be made clear in the instructions. (e.g. "Click and drag items in the list to re-order them. Once you're satisfied, click Download Pdf to get a printable reference card showing your selected candiate numbering.")
- the Download Pdf button should open a new window, not in current window. When going back from the pdf, the ordering is reset. This is frustrating.

**Comment by mipearson** [comment]
Agreed on both points. @jeamland?

**Comment by jeamland** [comment]
I can do it as a download, would that be acceptable @cofiem?

**Comment by cofiem** [comment]
I'm mainly concerned that the ordering does not reset after clicking the Download Pdf button, and  that people know to click the button to get reference ballot card. Your changes seem to solve both problems.
