### ISSUE TITLE
Missing candidate

### ISSUE THREAD

**Issue by AlanI-xx** [belowtheline/site_2014#17]
The Liberal candidate for Fowler appears to be missing: NGUYEN, Andrew

http://www.aec.gov.au/election/nsw/fowler.htm

I think it's because there's actually two separate Liberal candidates named "Andrew Nguyen", one for Fowler and another for Oxley -- I'd hazard a guess that the two people have mistakenly been merged into one due to the duplicate name/party.

Looks like the Liberal's official website creatively added the number '0' to the end of one of them in their URLs :)

http://www.liberal.org.au/member/andrew-nguyen
http://www.liberal.org.au/member/andrew-nguyen-0

Thought I'd better leave it to you guys to fix rather than making it worse.

Cheers,
- Alan

**Comment by jeamland** [comment]
Fixed. Thanks for spotting that.
